### ISSUE TITLE
Encodage

### ISSUE THREAD

**Issue by Helvethor** [oci1315/csudoci#1]
J'obtiens des erreurs d'encodage à l'utilisation du fichier htmltree.py. Ils sont résolus par l'ajout de "# coding=utf-8" en première ligne

**Comment by donnerc** [comment]
Il faut bien veiller à utiliser `python3` pour exécuter le script. Python 2 a des tas de problèmes avec les encodages de caractères et ne prend pas le utf-8 par défaut.
