### ISSUE TITLE
<!DOCTYPE html>

### ISSUE THREAD

**Issue by Helvethor** [oci1315/csudoci#3]
La création d'un arbre HTML lève une erreur lorsque <!DOCTYPE html> est placé en haut de page, comme il se doit.

**Comment by donnerc** [comment]
Merci pour l'info! C'est vrai que c'est pas très heureux comme comportement.

Saurais-tu indiquer un moyen de corriger cela?

**Comment by donnerc** [comment]
N'hésitez pas à forker le dépôt dans votre GitHub et apporter les corrections. Il suffit ensuite de faire une Pull Request sur ce dépôt et je pourrai merger vos correctifs.

**Comment by donnerc** [comment]
Cette issue est désormais fermée par le commit 28b5255f8093957ab1c6cc2eeaeee3d20ac0ef31
