### ISSUE TITLE
Toujours un problème avec le fichier parser.py

### ISSUE THREAD

**Issue by CottetE** [oci1315/csudoci#4]
Après avoir vérifié que les fichiers étaient à jour j'ai testé à nouveau avec le fichier `manip.py` et le problème déjà relevé qui est en copie ci-dessous revient. En mettant la fonction `handle_data(self, data)` entre `"""  """` dans le fichier `parser.py`, le problème ne change pas et non plus en mettant la classe `MyHTMLParseError(Exception)` entre `"""  """`, ceux qui est étrange puisque le message d'erreur les utilise ... 

``` python
>Traceback (most recent call last):
 File "manip.py", line 74, in <module>
    test()
  File "manip.py", line 63, in test
    tree = HTMLTreeParser(test_html).get_tree()
  File "/usr/local/lib/python3.4/dist-packages/csudoci/html/parser.py", line 22, in __init__
    self.feed(html)
  File "/usr/lib/python3.4/html/parser.py", line 165, in feed
    self.goahead(0)
  File "/usr/lib/python3.4/html/parser.py", line 216, in goahead
    **self.handle_data**(rawdata[i:j])
  File "/usr/local/lib/python3.4/dist-packages/csudoci/html/parser.py", line 90, in handle_data
    stack=self.stack
**csudoci.html.parser.MyHTMLParseError**: Trouvé les données '
    ' en dehors de toute balise
```

**Comment by donnerc** [comment]
Le code est fonctionnel et le problème a été corrigé dans l'issue #2 (commit 936ce83e8463fcfdaef15778909e55a3bd31da52)

Il ne faut cependant pas oublier d'installer la mise à jour avec 

``` bash
# à exécuter à l'intérieur du dépôt local
$ git pull
# à exécuter dans le dossier `csudoci` contenant le fichier `setup.py` pour mettre à jour la version du package installée
$ sudo python3 setup.py install
```
